name: Build fcct-online

on:
  push:
    branches: [ master ]
    paths:
      - 'fcct-online/**'
      - '.github/workflows/fcct-online.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push for fcct-online
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: fcct-online/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fcct-online:latest