name: Build hishtory

on:
  push:
    branches: [ master ]
    paths:
      - 'hishtory/**'
      - '.github/workflows/hishtory.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push for hishtory
        uses: docker/build-push-action@v2
        with:
          context: hishtory/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hishtory:latest
        continue-on-error: true
