name: Build nopasswd_sshd

on:
  push:
    branches: [ master ]
    paths:
      - 'nopasswd_sshd/**'
      - '.github/workflows/nopasswd_sshd.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push for nopasswd_sshd
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: nopasswd_sshd/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nopasswd_sshd:latest