name: Build registry-ui

on:
  push:
    branches: [ master ]
    paths:
      - 'registry-ui/**'
      - '.github/workflows/registry-ui.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push for registry-ui
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: registry-ui/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/registry-ui:latest